import Foundation
import HelixCore
import HelixDevProtocol

/// Secure discovery and pairing configuration for development sessions.
public enum DevConnection {}

extension DevConnection {
/// One-time invitation and pinned Host Identity used to begin a connection.
public struct Configuration: Hashable, Sendable,
    CustomStringConvertible, CustomDebugStringConvertible, CustomReflectable {
    /// Wire protocol version expected by both peers.
    public var protocolVersion: UInt16
    /// SHA-256 pin of the persistent Helix Host Identity SPKI.
    public var expectedSPKIHash: Core.Digest
    /// One-time code redeemed inside pinned TLS.
    public var pairingCode: Pairing.Code

    /// Creates and validates explicit pairing inputs.
    public init(
        protocolVersion: UInt16 = DevProtocol.Metadata.currentProtocolVersion,
        expectedSPKIHash: Core.Digest,
        pairingCode: Pairing.Code
    ) throws {
        self.protocolVersion = protocolVersion
        self.expectedSPKIHash = expectedSPKIHash
        self.pairingCode = pairingCode
        try validate()
    }

    /// Creates configuration from generated trust material and an entered code.
    public init(
        hubContract: DevRuntime.HubContract,
        pairingCode: Pairing.Code
    ) throws {
        try hubContract.validate()
        try self.init(
            protocolVersion: hubContract.protocolVersion,
            expectedSPKIHash: hubContract.expectedSPKIHash,
            pairingCode: pairingCode
        )
    }

    /// Rejects contracts generated by an incompatible protocol version.
    public func validate() throws {
        guard protocolVersion == DevProtocol.Metadata.currentProtocolVersion else {
            throw DevConnection.Error.protocolVersionMismatch
        }
    }

    public var description: String {
        "DevConnection.Configuration(protocolVersion: \(protocolVersion), "
            + "expectedSPKIHash: \(expectedSPKIHash.hex), pairingCode: <redacted>)"
    }

    public var debugDescription: String { description }

    /// Prevents generic reflection and dump utilities from exposing the code.
    public var customMirror: Mirror {
        Mirror(
            self,
            children: [
                "protocolVersion": protocolVersion,
                "expectedSPKIHash": expectedSPKIHash.hex,
                "pairingCode": "<redacted>",
            ],
            displayStyle: .struct
        )
    }
}

/// Connection setup and lifecycle failures surfaced to development integrations.
public enum Error: Swift.Error, Equatable, Sendable, CustomStringConvertible {
    /// Pairing input, retry limits, or generated values are invalid.
    case invalidConfiguration
    /// The App and Helix service use different development protocol versions.
    case protocolVersionMismatch
    /// Paired and authenticated session identities disagree.
    case sessionIdentityMismatch
    /// An Xcode-traced process has no build-scoped automatic invitation.
    case missingAutomaticInvitation
    /// Manual activation was requested from an automatic Xcode process.
    case manualActivationUnavailable
    /// A second connection was started while one was already running.
    case alreadyRunning
    /// Bonjour did not expose a pinned Helix service before the deadline.
    case discoveryTimedOut
    /// A pinned TLS connection did not become ready before its deadline.
    case connectionTimedOut
    /// The service did not answer a pairing request before its deadline.
    case pairingTimedOut
    /// The service rejected invitation redemption or lease resumption.
    case pairingRejected(Pairing.Rejection.Reason, String)
    /// The client or discovery operation was intentionally stopped.
    case stopped

    public var description: String {
        switch self {
        case .invalidConfiguration:
            "Helix Dev connection configuration is invalid"
        case .protocolVersionMismatch:
            "Helix Dev Protocol versions do not match"
        case .sessionIdentityMismatch:
            "the paired session does not belong to this App or Dev Shell"
        case .missingAutomaticInvitation:
            "this Xcode Run build has no automatic Helix invitation"
        case .manualActivationUnavailable:
            "manual pairing is available only when the test App is opened directly"
        case .alreadyRunning:
            "the Helix Dev connection client is already running"
        case .discoveryTimedOut:
            "the pinned Helix Bonjour service was not discovered in time"
        case .connectionTimedOut:
            "the Helix Dev TLS connection did not become ready in time"
        case .pairingTimedOut:
            "the Helix service did not answer pairing in time"
        case let .pairingRejected(reason, detail):
            "Helix pairing was rejected (\(reason.rawValue)): \(detail)"
        case .stopped:
            "the Helix Dev connection client was stopped"
        }
    }
}
}
