import Foundation
#if canImport(HelixCore)
import HelixCore
import HelixDevProtocol
#endif

#if canImport(Darwin)
import Darwin
#endif

extension DevRuntime {
/// Non-secret trust material compiled into one Helix-enabled development App.
///
/// The stable SPKI hash chooses the developer's Helix service. An automatic
/// code is emitted only for an Xcode Run build and is ignored when the same
/// installed App is opened later without a debugger.
public final class HubContract: Sendable, CustomStringConvertible,
    CustomDebugStringConvertible, CustomReflectable {
    /// Pairing protocol version understood by the generated contract.
    public let protocolVersion: UInt16
    /// Stable SHA-256 pin of the developer's persistent Helix Host Identity.
    public let expectedSPKIHash: Core.Digest
    /// One-time Xcode invitation, or `nil` for a manual-only test package.
    public let automaticPairingCode: Pairing.Code?

    /// Creates an explicit contract for generated code and advanced tests.
    public init(
        protocolVersion: UInt16 = DevProtocol.Metadata.currentProtocolVersion,
        expectedSPKIHash: Core.Digest,
        automaticPairingCode: Pairing.Code? = nil
    ) throws {
        self.protocolVersion = protocolVersion
        self.expectedSPKIHash = expectedSPKIHash
        self.automaticPairingCode = automaticPairingCode
        try validate()
    }

    /// Rejects contracts generated by an incompatible Helix toolchain.
    public func validate() throws {
        guard protocolVersion == DevProtocol.Metadata.currentProtocolVersion else {
            throw DevConnection.Error.protocolVersionMismatch
        }
    }

    public var description: String {
        let invitation = automaticPairingCode == nil ? "none" : "<redacted>"
        return "DevRuntime.HubContract(protocolVersion: \(protocolVersion), "
            + "expectedSPKIHash: \(expectedSPKIHash.hex), "
            + "automaticPairingCode: \(invitation))"
    }

    public var debugDescription: String { description }

    /// Prevents generic reflection and dump utilities from exposing an invitation.
    public var customMirror: Mirror {
        Mirror(
            self,
            children: [
                "protocolVersion": protocolVersion,
                "expectedSPKIHash": expectedSPKIHash.hex,
                "automaticPairingCode": automaticPairingCode == nil
                    ? "none" : "<redacted>",
            ],
            displayStyle: .class
        )
    }
}

/// Resolves the private Hub contract emitted into the generated Bridge object.
public enum LinkedHubContract {
    /// Stable process symbol supplied only by a Helix development build.
    public static let providerSymbol = "hlx_dev_hub_contract_v1"

    /// Loads and validates the single Hub contract linked into this process.
    public static func load() throws -> DevRuntime.HubContract {
        #if canImport(Darwin)
        guard let handle = dlopen(nil, RTLD_LAZY) else {
            throw DevRuntime.HubContractError.imageUnavailable
        }
        defer { dlclose(handle) }
        guard let symbol = dlsym(handle, providerSymbol) else {
            throw DevRuntime.HubContractError.providerMissing
        }
        typealias ProviderFactory = @convention(c) () -> UnsafeMutableRawPointer?
        let factory = unsafeBitCast(symbol, to: ProviderFactory.self)
        guard let pointer = factory() else {
            throw DevRuntime.HubContractError.providerMissing
        }
        let contract = Unmanaged<DevRuntime.HubContract>
            .fromOpaque(pointer).takeUnretainedValue()
        try contract.validate()
        return contract
        #else
        throw DevRuntime.HubContractError.imageUnavailable
        #endif
    }
}

public enum HubContractError: Swift.Error, Equatable, Sendable, CustomStringConvertible {
    case imageUnavailable
    case providerMissing

    public var description: String {
        switch self {
        case .imageUnavailable:
            "the current process image cannot be inspected for a Helix Hub contract"
        case .providerMissing:
            "the App does not contain a generated Helix Hub contract"
        }
    }
}
}
