#if canImport(Network) && canImport(Security) && canImport(UIKit) && canImport(SwiftUI)
import Foundation
#if canImport(HelixCore)
import HelixLiveReloadAPI
import HelixRuntime
import HelixVerifier
#endif

extension DevRuntime {
/// App-owned composition root for development activation, UI refresh, and Hub pairing.
///
/// Keep one session alive for the App process. Xcode launches connect
/// automatically; an installed test App opened directly stays offline until
/// ``connect(pairingCode:)`` is called from the App's debug UI.
///
/// ```swift
/// @MainActor
/// final class DevelopmentRuntimeOwner {
///     let session = try! DevRuntime.ApplicationSession()
///
///     func pair(code: String) async throws {
///         try await session.connect(pairingCode: code)
///     }
/// }
/// ```
@MainActor
public final class ApplicationSession {
    /// UI refresh, status, and debug-overlay environment owned by this session.
    public let environment: DevRuntime.LiveReloadEnvironment
    /// Runtime Engine that receives temporary development generations.
    public let runtime: Runtime.Engine
    /// Process-lifetime activation policy measured before any network access.
    public let launchMode: DevRuntime.LaunchMode
    /// Prepared connection graph, or `nil` when development runtime is disabled.
    public let bootstrap: DevRuntime.Bootstrap?

    /// Creates a Dev session from the hidden Bridge and Hub contract generated
    /// by the Helix Xcode integration.
    ///
    /// App code does not configure endpoints, credentials, or debugger scripts.
    /// `bridgeProvider` and `hubContract` are test seams; normal callers omit them.
    public convenience init(
        environment: DevRuntime.LiveReloadEnvironment = .init(),
        options: DevRuntime.Bootstrap.Options = .init(),
        bridgeProvider: Runtime.BridgeProvider? = nil,
        hubContract: DevRuntime.HubContract? = nil
    ) throws {
        let launchMode = DevRuntime.LaunchMode.current()
        let provider = try bridgeProvider ?? Runtime.LinkedBridge.load()
        let contract = try hubContract ?? DevRuntime.LinkedHubContract.load()
        let runtime = try provider.makeRuntime()
        try self.init(
            hubContract: contract,
            launchMode: launchMode,
            build: DevRuntime.BuildContract(bridge: provider.descriptor),
            runtime: runtime,
            shell: provider.makeShellInterface(),
            environment: environment,
            installBridge: provider.install(on:),
            options: options
        )
    }

    /// Creates a session from explicitly assembled Runtime components.
    ///
    /// This initializer is intended for tests and alternate build adapters. The
    /// supplied launch mode is immutable for the lifetime of the returned object.
    public init(
        hubContract: DevRuntime.HubContract,
        launchMode: DevRuntime.LaunchMode,
        build: DevRuntime.BuildContract,
        runtime: Runtime.Engine,
        shell: Verification.ShellInterface,
        environment: DevRuntime.LiveReloadEnvironment = .init(),
        installBridge: (Runtime.Engine) throws -> Void,
        options: DevRuntime.Bootstrap.Options = .init()
    ) throws {
        try installBridge(runtime)
        self.environment = environment
        self.runtime = runtime
        self.launchMode = launchMode
        bootstrap = try DevRuntime.Bootstrap.prepare(
            hubContract: hubContract,
            launchMode: launchMode,
            build: build,
            runtime: runtime,
            shell: shell,
            liveReloadEnvironment: environment,
            options: options
        )
    }

    /// Enables discovery and pairs a directly opened test App with Helix Hub.
    ///
    /// The code is four characters, case-insensitive, and generated by the Mac
    /// app. Calling this from an Xcode-launched process fails because that launch
    /// already uses its build-scoped automatic invitation.
    public func connect(pairingCode: String) async throws {
        guard let bootstrap else { throw DevRuntime.BootstrapError.disabled }
        try await bootstrap.connect(pairingCode: pairingCode)
    }

    /// Stops discovery, transport, and the debug overlay. It is safe to repeat.
    public func stop() async {
        await bootstrap?.stop()
    }
}
}
#endif
