import Foundation
import HelixCore
import HelixDevProtocol

extension DevSession {
/// A lightweight, persistent pointer to one fully prepared development Shell.
public struct BuildContext: Codable, Hashable, Sendable {
    public static let currentSchemaVersion: UInt16 = 1

    /// Build-context document schema.
    public var schemaVersion: UInt16
    /// Exact linked Shell and peer build identity.
    public var shellIdentity: DevProtocol.ShellIdentity
    /// SHA-256 of the standardized workspace path.
    public var workspacePathHash: Core.Digest
    /// Standardized absolute workspace or project path.
    public var workspacePath: String
    /// Absolute path of the prepared `HelixDev.json` document.
    public var configurationPath: String
    /// Xcode scheme used for this Shell.
    public var scheme: String
    /// Xcode build configuration used for this Shell.
    public var buildConfiguration: String
    /// Swift module providing the reloadable Feature.
    public var moduleName: String
    /// Time at which this context became available to the service.
    public var registeredAt: Date

    /// Creates a context from already verified build metadata.
    public init(
        schemaVersion: UInt16 = Self.currentSchemaVersion,
        shellIdentity: DevProtocol.ShellIdentity,
        workspacePathHash: Core.Digest,
        workspacePath: String,
        configurationPath: String,
        scheme: String,
        buildConfiguration: String,
        moduleName: String,
        registeredAt: Date = Date()
    ) {
        self.schemaVersion = schemaVersion
        self.shellIdentity = shellIdentity
        self.workspacePathHash = workspacePathHash
        self.workspacePath = workspacePath
        self.configurationPath = configurationPath
        self.scheme = scheme
        self.buildConfiguration = buildConfiguration
        self.moduleName = moduleName
        self.registeredAt = registeredAt
    }

    /// Loads, verifies, and indexes a configuration generated by an Xcode build.
    public static func load(
        configurationURL: URL,
        workspaceURL: URL,
        registeredAt: Date = Date()
    ) throws -> Self {
        let configurationURL = configurationURL.standardizedFileURL
        let workspaceURL = workspaceURL.standardizedFileURL
        let prepared = try DevSession.PreparedConfiguration.load(
            configurationURL: configurationURL
        )
        let workspaceHash = Core.Digest.sha256(workspaceURL.path)
        guard workspaceHash == prepared.manifest.workspacePathHash else {
            throw DevSession.ContextError.workspaceMismatch
        }
        let context = Self(
            shellIdentity: prepared.shellIdentity,
            workspacePathHash: workspaceHash,
            workspacePath: workspaceURL.path,
            configurationPath: configurationURL.path,
            scheme: prepared.manifest.scheme,
            buildConfiguration: prepared.manifest.configuration,
            moduleName: prepared.manifest.moduleName,
            registeredAt: registeredAt
        )
        try context.validate()
        return context
    }

    /// Reopens the prepared artifacts and confirms that none changed identity.
    public func loadPreparedConfiguration() throws -> DevSession.PreparedConfiguration {
        try validate()
        let prepared = try DevSession.PreparedConfiguration.load(
            configurationURL: URL(fileURLWithPath: configurationPath)
        )
        guard prepared.shellIdentity == shellIdentity,
              prepared.manifest.workspacePathHash == workspacePathHash,
              prepared.manifest.scheme == scheme,
              prepared.manifest.configuration == buildConfiguration,
              prepared.manifest.moduleName == moduleName
        else {
            throw DevSession.ContextError.buildIdentityMismatch
        }
        return prepared
    }

    /// Validates bounded metadata and exact workspace derivation.
    public func validate() throws {
        guard schemaVersion == Self.currentSchemaVersion else {
            throw DevSession.ContextError.unsupportedSchema(schemaVersion)
        }
        try shellIdentity.validate()
        let standardizedWorkspace = URL(fileURLWithPath: workspacePath)
            .standardizedFileURL.path
        let standardizedConfiguration = URL(fileURLWithPath: configurationPath)
            .standardizedFileURL.path
        guard Self.isAbsolutePath(workspacePath),
              Self.isAbsolutePath(configurationPath),
              workspacePath == standardizedWorkspace,
              configurationPath == standardizedConfiguration,
              Core.Digest.sha256(standardizedWorkspace) == workspacePathHash,
              [scheme, buildConfiguration, moduleName].allSatisfy(Self.isSafeText),
              registeredAt.timeIntervalSinceReferenceDate.isFinite
        else {
            throw DevSession.ContextError.invalidValue
        }
    }

    /// Returns whether a pre-authentication peer is this exact build.
    public func matches(_ peer: DevProtocol.PeerBuildIdentity) -> Bool {
        shellIdentity.matches(peer)
    }

    private static func isAbsolutePath(_ value: String) -> Bool {
        value.hasPrefix("/") && value.utf8.count <= 4_096
            && !value.unicodeScalars.contains(where: { $0.value == 0 })
    }

    private static func isSafeText(_ value: String) -> Bool {
        !value.isEmpty && value.utf8.count <= 1_024
            && !value.unicodeScalars.contains(where: { $0.value == 0 })
    }
}

public enum ContextError: Swift.Error, Equatable, Sendable, CustomStringConvertible {
    case unsupportedSchema(UInt16)
    case invalidValue
    case workspaceMismatch
    case buildIdentityMismatch
    case shellIdentityCollision
    case buildIdentityCollision
    case documentTooLarge
    case invalidDocument(String)

    public var description: String {
        switch self {
        case let .unsupportedSchema(version):
            "unsupported Build Context schema \(version)"
        case .invalidValue:
            "Build Context contains invalid or unsafe metadata"
        case .workspaceMismatch:
            "Build Context workspace does not match the captured Dev Manifest"
        case .buildIdentityMismatch:
            "Build Context no longer resolves to its registered Shell identity"
        case .shellIdentityCollision:
            "one Shell ID was registered with conflicting build identities"
        case .buildIdentityCollision:
            "one peer build identity was registered by multiple Shells"
        case .documentTooLarge:
            "Build Context registry exceeds its size limit"
        case let .invalidDocument(reason):
            "invalid Build Context registry: \(reason)"
        }
    }
}
}
