import HelixBytecode
import HelixCore
import HelixInterface

extension BridgeGeneration {
/// Swift source fragments required to route property observer bodies through
/// the permanent Shell Bridge without relying on observer dynamic replacement.
public struct ObserverTransform: Sendable {
    public var bodies: [Core.FunctionKey: String]
    public var supplementalDeclarations: [String: String]

    public init(
        bodies: [Core.FunctionKey: String],
        supplementalDeclarations: [String: String]
    ) {
        self.bodies = bodies
        self.supplementalDeclarations = supplementalDeclarations
    }
}
}

extension BridgeGeneration.Generator {
    /// Renders observer dispatch bodies in their original source context. The
    /// Swift frontend cannot reliably compile observer-only
    /// `@_dynamicReplacement` declarations in normal multi-file builds, while
    /// an in-place body keeps storage, privacy, and observer recursion rules
    /// exact.
    public func renderObserverTransform(
        archive: InterfaceArchive.Archive,
        roots: [BridgeGeneration.Root]
    ) throws -> BridgeGeneration.ObserverTransform {
        try archive.validate()
        let observerRoots = roots.filter {
            $0.sourceDeclaration.kind == .propertyObservers
        }
        guard !observerRoots.isEmpty else {
            return .init(bodies: [:], supplementalDeclarations: [:])
        }
        guard Set(observerRoots.map(\.functionKey)).count == observerRoots.count else {
            throw BridgeGeneration.Error.incompleteRootSet
        }

        let records = Dictionary(
            uniqueKeysWithValues: archive.functions.map { ($0.key, $0) }
        )
        let frozenValueTypes = Dictionary(
            uniqueKeysWithValues: archive.frozenValueTypes.map { ($0.key, $0) }
        )
        for root in observerRoots {
            guard let record = records[root.functionKey],
                record.entryIndex == root.entryIndex,
                record.sourceFileLogicalID == root.sourceFileLogicalID
            else {
                throw BridgeGeneration.Error.rootDoesNotMatchArchive(root.functionKey)
            }
            try validateRoot(
                root,
                record: record,
                archive: archive,
                frozenValueTypes: frozenValueTypes
            )
        }

        let bodies = try Dictionary(uniqueKeysWithValues: observerRoots.map { root in
            guard let record = records[root.functionKey] else {
                throw BridgeGeneration.Error.rootDoesNotMatchArchive(root.functionKey)
            }
            let statements = try renderReplacementBody(
                root,
                record: record,
                frozenValueTypes: frozenValueTypes
            )
            return (root.functionKey, "{\n\(indentObserver(statements, spaces: 4))\n}")
        })
        let requiredFrozenValues = try requiredFrozenValueTypes(
            for: observerRoots,
            records: records,
            frozenValueTypes: frozenValueTypes
        )
        let frozenValuesBySource = Dictionary(
            grouping: requiredFrozenValues,
            by: \.sourceFileLogicalID
        )
        let sourceFileLogicalIDs = Set(observerRoots.map(\.sourceFileLogicalID))
            .union(frozenValuesBySource.keys)
        let supplementalDeclarations = try Dictionary(
            uniqueKeysWithValues: sourceFileLogicalIDs.sorted().map { sourceFileLogicalID in
                let codecs = try (frozenValuesBySource[sourceFileLogicalID] ?? [])
                    .sorted(by: { $0.key < $1.key }).map {
                        try renderFrozenValueCodec(
                            $0,
                            frozenValueTypes: frozenValueTypes
                        )
                    }
                let codecContainer = codecs.isEmpty ? "" : """
                    enum \(BridgeGeneration.GeneratedNativeType.groupName(
                        sourceFileLogicalID: sourceFileLogicalID
                    )) {
                    \(indentObserver(codecs.joined(separator: "\n\n"), spaces: 4))
                    }
                    """
                let source = [
                    "// Generated by Helix inside the original module. Do not edit.",
                    BridgeGeneration.RuntimeImports.production,
                    codecContainer,
                ].filter { !$0.isEmpty }.joined(separator: "\n\n")
                return (sourceFileLogicalID, source)
            }
        )
        return .init(
            bodies: bodies,
            supplementalDeclarations: supplementalDeclarations
        )
    }

    /// Codecs must remain in each value's defining source file so private
    /// stored state stays source-accessible. Include the full transitive value
    /// graph even when a dependency's file has no observer of its own.
    private func requiredFrozenValueTypes(
        for roots: [BridgeGeneration.Root],
        records: [Core.FunctionKey: InterfaceArchive.FunctionRecord],
        frozenValueTypes: [
            Bytecode.LocalTypeKey: InterfaceArchive.FrozenValueTypeRecord
        ]
    ) throws -> [InterfaceArchive.FrozenValueTypeRecord] {
        var required = Set<Bytecode.LocalTypeKey>()
        func collect(_ type: Bytecode.ValueType) throws {
            switch type {
            case let .local(key):
                guard required.insert(key).inserted else { return }
                guard let record = frozenValueTypes[key] else {
                    throw BridgeGeneration.Error.frozenValueTypeMismatch(key)
                }
                switch record.kind {
                case let .structure(fields):
                    for field in fields { try collect(field.type) }
                case let .enumeration(cases):
                    for payload in cases.compactMap(\.payloadType) {
                        try collect(payload)
                    }
                }
            case let .array(element), let .optional(element), let .set(element):
                try collect(element)
            case let .dictionary(key, value):
                try collect(key)
                try collect(value)
            case let .tuple(elements):
                for element in elements { try collect(element) }
            default:
                break
            }
        }
        for root in roots {
            guard let record = records[root.functionKey] else {
                throw BridgeGeneration.Error.rootDoesNotMatchArchive(root.functionKey)
            }
            for type in record.parameterTypes + [record.resultType] {
                try collect(type)
            }
        }
        return required.compactMap { frozenValueTypes[$0] }
    }

    private func indentObserver(_ value: String, spaces: Int) -> String {
        let prefix = String(repeating: " ", count: spaces)
        return value.split(separator: "\n", omittingEmptySubsequences: false)
            .map { prefix + $0 }
            .joined(separator: "\n")
    }
}
