import Foundation
import HelixCore

extension Pairing {
/// How an invitation is intended to activate a development session.
public enum Kind: String, Codable, CaseIterable, Hashable, Sendable {
    /// Generated by an Xcode build and consumed only for that debugger launch.
    case automaticXcode
    /// Displayed by Helix Hub and entered explicitly in the App.
    case manual
}

/// A short code reserved before the final executable identity is available.
public struct Reservation: Codable, Hashable, Sendable {
    public var invitationID: DevProtocol.InvitationID
    public var code: Pairing.Code
    public var kind: Pairing.Kind
    public var reservedAt: Date

    public init(
        invitationID: DevProtocol.InvitationID,
        code: Pairing.Code,
        kind: Pairing.Kind,
        reservedAt: Date
    ) {
        self.invitationID = invitationID
        self.code = code
        self.kind = kind
        self.reservedAt = reservedAt
    }

    /// Validates the identifier and timestamp carried across build phases.
    public func validate() throws {
        guard !Self.isZero(invitationID.rawValue), Self.isFinite(reservedAt) else {
            throw DevProtocol.Error.malformedMessage("pairing reservation is invalid")
        }
    }
}

/// A reservation bound to one exact, fully linked development Shell.
public struct Invitation: Codable, Hashable, Sendable {
    public var reservation: Pairing.Reservation
    public var shellIdentity: DevProtocol.ShellIdentity
    public var expiresAt: Date

    public init(
        reservation: Pairing.Reservation,
        shellIdentity: DevProtocol.ShellIdentity,
        expiresAt: Date
    ) {
        self.reservation = reservation
        self.shellIdentity = shellIdentity
        self.expiresAt = expiresAt
    }

    public var invitationID: DevProtocol.InvitationID { reservation.invitationID }
    public var code: Pairing.Code { reservation.code }
    public var kind: Pairing.Kind { reservation.kind }

    /// Validates reservation, Shell identity, and expiry ordering.
    public func validate() throws {
        try reservation.validate()
        try shellIdentity.validate()
        guard Self.isFinite(expiresAt), expiresAt > reservation.reservedAt else {
            throw DevProtocol.Error.malformedMessage("pairing invitation expiry is invalid")
        }
    }
}

/// First authenticated App request sent inside host-pinned TLS.
public struct RedeemRequest: Codable, Hashable, Sendable {
    public var code: Pairing.Code
    public var peerIdentity: DevProtocol.PeerIdentity
    public var clientNonce: Data

    public init(
        code: Pairing.Code,
        peerIdentity: DevProtocol.PeerIdentity,
        clientNonce: Data
    ) {
        self.code = code
        self.peerIdentity = peerIdentity
        self.clientNonce = clientNonce
    }

    /// Validates the peer identity and fixed-size nonce.
    public func validate() throws {
        try peerIdentity.validate()
        guard clientNonce.count == 32 else {
            throw DevProtocol.Error.invalidNonceLength
        }
    }
}

/// Secret-bearing response issued after a one-time code is consumed.
public struct SessionGrant: Codable, Hashable, Sendable {
    public var shellID: DevProtocol.ShellID
    public var leaseID: DevProtocol.LeaseID
    public var sessionSecret: Data
    public var serverNonce: Data
    public var expiresAt: Date
    public var proof: Data

    public init(
        shellID: DevProtocol.ShellID,
        leaseID: DevProtocol.LeaseID,
        sessionSecret: Data,
        serverNonce: Data,
        expiresAt: Date,
        proof: Data
    ) {
        self.shellID = shellID
        self.leaseID = leaseID
        self.sessionSecret = sessionSecret
        self.serverNonce = serverNonce
        self.expiresAt = expiresAt
        self.proof = proof
    }

    /// Validates identifier, nonce, secret, proof, and timestamp shapes.
    public func validate() throws {
        guard !Self.isZero(shellID.rawValue), !Self.isZero(leaseID.rawValue),
              sessionSecret.count == 32, serverNonce.count == 32,
              proof.count == 32, Self.isFinite(expiresAt)
        else {
            throw DevProtocol.Error.malformedMessage("pairing session grant is invalid")
        }
    }

    /// Verifies expiry and the TLS-exporter-bound response proof.
    public func verify(
        request: Pairing.RedeemRequest,
        tlsExporterHash: Core.Digest,
        now: Date = Date()
    ) throws -> Bool {
        try validate()
        try request.validate()
        guard now.timeIntervalSinceReferenceDate.isFinite, now <= expiresAt else {
            return false
        }
        let expected = try Pairing.Proof.sessionGrant(
            request: request,
            shellID: shellID,
            leaseID: leaseID,
            sessionSecret: sessionSecret,
            serverNonce: serverNonce,
            expiresAt: expiresAt,
            tlsExporterHash: tlsExporterHash
        )
        return DevProtocol.FrameCodec.constantTimeEqual(proof, expected)
    }
}

/// Proof that a reconnecting process still owns an active session secret.
public struct ResumeRequest: Codable, Hashable, Sendable {
    public var leaseID: DevProtocol.LeaseID
    public var peerIdentity: DevProtocol.PeerIdentity
    public var clientNonce: Data
    public var proof: Data

    public init(
        leaseID: DevProtocol.LeaseID,
        peerIdentity: DevProtocol.PeerIdentity,
        clientNonce: Data,
        proof: Data
    ) {
        self.leaseID = leaseID
        self.peerIdentity = peerIdentity
        self.clientNonce = clientNonce
        self.proof = proof
    }

    /// Creates a request bound to the new TLS connection and peer identity.
    public static func signed(
        leaseID: DevProtocol.LeaseID,
        peerIdentity: DevProtocol.PeerIdentity,
        sessionSecret: Data,
        tlsExporterHash: Core.Digest,
        clientNonce: Data? = nil
    ) throws -> Self {
        let nonce = try clientNonce ?? DevProtocol.SecureRandom.bytes(count: 32)
        let proof = try Pairing.Proof.resumeRequest(
            leaseID: leaseID,
            peerIdentity: peerIdentity,
            clientNonce: nonce,
            sessionSecret: sessionSecret,
            tlsExporterHash: tlsExporterHash
        )
        return .init(
            leaseID: leaseID,
            peerIdentity: peerIdentity,
            clientNonce: nonce,
            proof: proof
        )
    }

    /// Validates identifier, peer, nonce, and proof shapes.
    public func validate() throws {
        guard !Self.isZero(leaseID.rawValue), clientNonce.count == 32,
              proof.count == 32
        else {
            throw DevProtocol.Error.malformedMessage("pairing resume request is invalid")
        }
        try peerIdentity.validate()
    }
}

/// Server proof returned after successful lease resumption.
public struct ResumeGrant: Codable, Hashable, Sendable {
    public var shellID: DevProtocol.ShellID
    public var leaseID: DevProtocol.LeaseID
    public var serverNonce: Data
    public var expiresAt: Date
    public var proof: Data

    public init(
        shellID: DevProtocol.ShellID,
        leaseID: DevProtocol.LeaseID,
        serverNonce: Data,
        expiresAt: Date,
        proof: Data
    ) {
        self.shellID = shellID
        self.leaseID = leaseID
        self.serverNonce = serverNonce
        self.expiresAt = expiresAt
        self.proof = proof
    }

    /// Validates identifier, nonce, proof, and timestamp shapes.
    public func validate() throws {
        guard !Self.isZero(shellID.rawValue), !Self.isZero(leaseID.rawValue),
              serverNonce.count == 32, proof.count == 32, Self.isFinite(expiresAt)
        else {
            throw DevProtocol.Error.malformedMessage("pairing resume grant is invalid")
        }
    }

    /// Verifies expiry and the TLS-exporter-bound response proof.
    public func verify(
        request: Pairing.ResumeRequest,
        tlsExporterHash: Core.Digest,
        sessionSecret: Data,
        now: Date = Date()
    ) throws -> Bool {
        try validate()
        try request.validate()
        guard now.timeIntervalSinceReferenceDate.isFinite, now <= expiresAt else {
            return false
        }
        let expected = try Pairing.Proof.resumeGrant(
            request: request,
            shellID: shellID,
            serverNonce: serverNonce,
            expiresAt: expiresAt,
            sessionSecret: sessionSecret,
            tlsExporterHash: tlsExporterHash
        )
        return DevProtocol.FrameCodec.constantTimeEqual(proof, expected)
    }
}

/// Bounded, user-presentable reason that pairing failed.
public struct Rejection: Codable, Hashable, Sendable {
    public enum Reason: String, Codable, Hashable, Sendable {
        case invalidInvitation
        case expiredInvitation
        case buildMismatch
        case attemptLimitReached
        case invalidLease
        case protocolMismatch
    }

    public var reason: Reason
    public var detail: String

    public init(reason: Reason, detail: String) {
        self.reason = reason
        self.detail = detail
    }

    public init(_ failure: Pairing.Failure) {
        self.init(reason: failure.reason, detail: failure.detail)
    }

    fileprivate func validate() throws {
        guard !detail.isEmpty, detail.utf8.count <= 4_096,
              !detail.unicodeScalars.contains(where: { $0.value == 0 })
        else {
            throw DevProtocol.Error.malformedMessage("pairing rejection is invalid")
        }
    }
}

/// Messages permitted before the authenticated Dev Protocol begins.
public enum Message: Codable, Hashable, Sendable {
    case redeem(Pairing.RedeemRequest)
    case resume(Pairing.ResumeRequest)
    case sessionGranted(Pairing.SessionGrant)
    case sessionResumed(Pairing.ResumeGrant)
    case rejected(Pairing.Rejection)

    /// Validates the associated message payload.
    public func validate() throws {
        switch self {
        case let .redeem(request): try request.validate()
        case let .resume(request): try request.validate()
        case let .sessionGranted(grant): try grant.validate()
        case let .sessionResumed(grant): try grant.validate()
        case let .rejected(rejection): try rejection.validate()
        }
    }
}

/// Privacy-preserving stable key for one network source.
public struct RateLimitKey: Hashable, Sendable, CustomStringConvertible {
    private let digest: Core.Digest

    /// Hashes a normalized endpoint or other stable source identifier.
    public init(stableSource: String) {
        var hasher = Core.StableHasher(domain: "HLX.PairingRateLimit.v1")
        hasher.append(stableSource)
        digest = hasher.finalize()
    }

    public var description: String { digest.hex }
}

/// Structured failure used internally and mapped to ``Rejection`` on the wire.
public struct Failure: Swift.Error, Equatable, Sendable, CustomStringConvertible {
    public var reason: Pairing.Rejection.Reason
    public var detail: String

    public init(reason: Pairing.Rejection.Reason, detail: String) {
        self.reason = reason
        self.detail = detail
    }

    public var description: String { "\(reason.rawValue): \(detail)" }
}
}

extension Pairing {
enum Proof {
    static func sessionGrant(
        request: Pairing.RedeemRequest,
        shellID: DevProtocol.ShellID,
        leaseID: DevProtocol.LeaseID,
        sessionSecret: Data,
        serverNonce: Data,
        expiresAt: Date,
        tlsExporterHash: Core.Digest
    ) throws -> Data {
        try DevProtocol.FrameCodec.validateSecret(sessionSecret)
        var hasher = Core.StableHasher(domain: "HLX.PairingGrant.v1")
        hasher.append(try Core.CanonicalJSON.encode(request))
        hasher.append(shellID.rawValue.uuidString)
        hasher.append(leaseID.rawValue.uuidString)
        hasher.append(serverNonce)
        hasher.append(expiresAt.timeIntervalSinceReferenceDate.bitPattern)
        hasher.append(tlsExporterHash)
        return DevProtocol.FrameCodec.authenticationTag(
            domain: "HLX.PairingGrantProof.v1",
            body: hasher.finalize().data,
            secret: sessionSecret
        )
    }

    static func resumeRequest(
        leaseID: DevProtocol.LeaseID,
        peerIdentity: DevProtocol.PeerIdentity,
        clientNonce: Data,
        sessionSecret: Data,
        tlsExporterHash: Core.Digest
    ) throws -> Data {
        try DevProtocol.FrameCodec.validateSecret(sessionSecret)
        var hasher = Core.StableHasher(domain: "HLX.PairingResumeRequest.v1")
        hasher.append(leaseID.rawValue.uuidString)
        hasher.append(try Core.CanonicalJSON.encode(peerIdentity))
        hasher.append(clientNonce)
        hasher.append(tlsExporterHash)
        return DevProtocol.FrameCodec.authenticationTag(
            domain: "HLX.PairingResumeRequestProof.v1",
            body: hasher.finalize().data,
            secret: sessionSecret
        )
    }

    static func resumeGrant(
        request: Pairing.ResumeRequest,
        shellID: DevProtocol.ShellID,
        serverNonce: Data,
        expiresAt: Date,
        sessionSecret: Data,
        tlsExporterHash: Core.Digest
    ) throws -> Data {
        try DevProtocol.FrameCodec.validateSecret(sessionSecret)
        var hasher = Core.StableHasher(domain: "HLX.PairingResumeGrant.v1")
        hasher.append(try Core.CanonicalJSON.encode(request))
        hasher.append(shellID.rawValue.uuidString)
        hasher.append(serverNonce)
        hasher.append(expiresAt.timeIntervalSinceReferenceDate.bitPattern)
        hasher.append(tlsExporterHash)
        return DevProtocol.FrameCodec.authenticationTag(
            domain: "HLX.PairingResumeGrantProof.v1",
            body: hasher.finalize().data,
            secret: sessionSecret
        )
    }
}
}

private extension Pairing.Reservation {
    static func isFinite(_ date: Date) -> Bool {
        date.timeIntervalSinceReferenceDate.isFinite
    }

    static func isZero(_ value: UUID) -> Bool {
        value == UUID(uuid: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))
    }
}

private extension Pairing.Invitation {
    static func isFinite(_ date: Date) -> Bool {
        date.timeIntervalSinceReferenceDate.isFinite
    }
}

private extension Pairing.SessionGrant {
    static func isFinite(_ date: Date) -> Bool {
        date.timeIntervalSinceReferenceDate.isFinite
    }

    static func isZero(_ value: UUID) -> Bool {
        value == UUID(uuid: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))
    }
}

private extension Pairing.ResumeRequest {
    static func isZero(_ value: UUID) -> Bool {
        value == UUID(uuid: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))
    }
}

private extension Pairing.ResumeGrant {
    static func isFinite(_ date: Date) -> Bool {
        date.timeIntervalSinceReferenceDate.isFinite
    }

    static func isZero(_ value: UUID) -> Bool {
        value == UUID(uuid: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))
    }
}
