import Foundation
import HelixBuildTools
import HelixCore

extension Hub {
/// Records only files wholly generated by Hub. It lets reconfiguration and
/// removal clean obsolete implementation files without enumerating or claiming
/// unknown files that happen to share the integration directory.
struct GeneratedFileManifest: Codable, Hashable, Sendable {
    struct File: Codable, Hashable, Sendable {
        var path: String
        var byteCount: UInt64
        var sha256: Core.Digest
        var permissions: UInt16
    }

    static let currentSchemaVersion: UInt16 = 1
    static let fileName = "GeneratedFiles.json"
    static let maximumDocumentBytes = 2 * 1_024 * 1_024

    var schemaVersion: UInt16
    var projectPath: String
    var integrationRoot: String
    var files: [File]

    init(
        plan: XcodeIntegration.HostPlan,
        mutations: [Hub.FileMutation]
    ) throws {
        try plan.validate()
        let prefix = plan.integrationRoot + "/"
        let owned = mutations.filter { $0.relativePath.hasPrefix(prefix) }
        schemaVersion = Self.currentSchemaVersion
        projectPath = plan.projectPath
        integrationRoot = plan.integrationRoot
        files = try owned.map { mutation in
            guard (0...0o777).contains(mutation.permissions) else {
                throw Hub.Error.transactionFailed(
                    "generated file has invalid permissions: \(mutation.relativePath)"
                )
            }
            return File(
                path: mutation.relativePath,
                byteCount: UInt64(mutation.data.count),
                sha256: .sha256(mutation.data),
                permissions: UInt16(mutation.permissions)
            )
        }.sorted { $0.path < $1.path }
        try validate(for: plan)
    }

    func encoded(for plan: XcodeIntegration.HostPlan) throws -> Data {
        try validate(for: plan)
        let data = try Core.CanonicalJSON.encode(self)
        guard data.count <= Self.maximumDocumentBytes else {
            throw Hub.Error.transactionFailed(
                "generated-file ownership manifest is oversized"
            )
        }
        return data
    }

    static func decode(
        _ data: Data,
        for plan: XcodeIntegration.HostPlan
    ) throws -> Self {
        guard !data.isEmpty, data.count <= maximumDocumentBytes else {
            throw Hub.Error.transactionFailed(
                "generated-file ownership manifest is empty or oversized"
            )
        }
        let manifest: Self
        do {
            manifest = try JSONDecoder().decode(Self.self, from: data)
        } catch {
            throw Hub.Error.transactionFailed(
                "generated-file ownership manifest is invalid"
            )
        }
        guard try Core.CanonicalJSON.encode(manifest) == data else {
            throw Hub.Error.transactionFailed(
                "generated-file ownership manifest is noncanonical"
            )
        }
        try manifest.validate(for: plan)
        return manifest
    }

    private func validate(for plan: XcodeIntegration.HostPlan) throws {
        let paths = files.map(\.path)
        guard schemaVersion == Self.currentSchemaVersion,
              projectPath == plan.projectPath,
              integrationRoot == plan.integrationRoot,
              files.count <= 8_192,
              files == files.sorted(by: { $0.path < $1.path }),
              Set(paths).count == paths.count,
              files.allSatisfy({ file in
                  Self.isSafePath(file.path, beneath: integrationRoot)
                      && file.byteCount <= 64 * 1_024 * 1_024
                      && file.permissions <= 0o777
              })
        else {
            throw Hub.Error.transactionFailed(
                "generated-file ownership manifest does not match this project"
            )
        }
    }

    private static func isSafePath(_ path: String, beneath root: String) -> Bool {
        guard path.hasPrefix(root + "/"),
              !path.contains("\\"), !path.contains("\0")
        else { return false }
        let components = path.split(separator: "/", omittingEmptySubsequences: false)
        return !components.contains("")
            && !components.contains(".")
            && !components.contains("..")
    }
}
}
