#if os(macOS)
import Foundation
import HelixBuildTools

extension Hub {
struct SchemeDocument {
    // Scheme scriptText is an XML attribute, whose whitespace is normalized on
    // parse. A one-line shell no-op survives arbitrary XML round trips while
    // still giving ownership checks an exact, non-title marker.
    private static let ownedScriptMarker =
        ": \"Generated by Helix Hub. Do not edit.\";"
    private let document: XMLDocument

    init(data: Data) throws {
        do {
            document = try XMLDocument(
                data: data,
                options: [.nodePreserveWhitespace, .nodePreserveAttributeOrder]
            )
        } catch {
            throw Hub.Error.invalidProject("shared Xcode scheme is malformed XML")
        }
        guard document.rootElement()?.name == "Scheme" else {
            throw Hub.Error.invalidProject("shared Xcode scheme has no Scheme root")
        }
    }

    func configure(
        profile: XcodeIntegration.Profile,
        applicationTarget: Hub.XcodeTarget,
        projectName: String,
        integrationRoot: String
    ) throws -> Data {
        try configure(
            profiles: [profile],
            applicationTargets: [profile.applicationTargetName: applicationTarget],
            projectName: projectName,
            integrationRoot: integrationRoot
        )
    }

    func configure(
        profiles: [XcodeIntegration.Profile],
        applicationTargets: [String: Hub.XcodeTarget],
        projectName: String,
        integrationRoot: String
    ) throws -> Data {
        guard !profiles.isEmpty else {
            throw Hub.Error.invalidOnboarding("a shared scheme has no Helix profiles")
        }
        let buildAction = try requiredElement("BuildAction")
        removeOwnedAction(from: buildAction, containerName: "PreActions")
        removeOwnedAction(from: buildAction, containerName: "PostActions")
        let launchAction = document.rootElement()?.elements(forName: "LaunchAction").first
        if let launchAction {
            removeOwnedAction(from: launchAction, containerName: "PreActions")
        }
        for profile in profiles.sorted(by: { $0.id < $1.id }) {
            guard let applicationTarget = applicationTargets[profile.applicationTargetName]
            else {
                throw Hub.Error.invalidOnboarding(
                    "profile \(profile.id) has no application target"
                )
            }
            switch profile.workflow {
            case .hotPatch:
                appendAction(
                    owner: buildAction,
                    containerName: "PostActions",
                    title: "Helix Hub: Audit \(profile.id)",
                    script: phaseScript(
                        profile: profile,
                        phase: "audit",
                        integrationRoot: integrationRoot
                    ),
                    target: applicationTarget,
                    projectName: projectName
                )
            case .liveReload:
                guard let launchAction else {
                    throw Hub.Error.invalidProject("shared scheme has no LaunchAction")
                }
                appendAction(
                    owner: launchAction,
                    containerName: "PreActions",
                    title: "Helix Hub: Register \(profile.id)",
                    script: phaseScript(
                        profile: profile,
                        phase: "live-register",
                        integrationRoot: integrationRoot
                    ),
                    target: applicationTarget,
                    projectName: projectName
                )
            }
        }
        return try serialized()
    }

    /// Removes only Hub-owned actions and preserves every user-authored scheme
    /// setting. This makes moving a workflow to another scheme reversible.
    func removingOwnedActions() throws -> Data {
        if let buildAction = document.rootElement()?.elements(forName: "BuildAction").first {
            removeOwnedAction(from: buildAction, containerName: "PreActions")
            removeOwnedAction(from: buildAction, containerName: "PostActions")
        }
        if let launchAction = document.rootElement()?
            .elements(forName: "LaunchAction").first {
            removeOwnedAction(from: launchAction, containerName: "PreActions")
            removeOwnedAction(from: launchAction, containerName: "PostActions")
        }
        return try serialized()
    }

    func containsOwnedAction(titled title: String) -> Bool {
        let nodes = (try? document.nodes(forXPath: "//ActionContent")) ?? []
        return nodes.contains { node in
            guard let content = node as? XMLElement else { return false }
            return content.attribute(forName: "title")?.stringValue == title
                && isOwned(content)
        }
    }

    private func serialized() throws -> Data {
        let result = document.xmlData(options: [.nodePrettyPrint])
        guard result.count <= 8 * 1_024 * 1_024 else {
            throw Hub.Error.invalidProject("shared Xcode scheme is unexpectedly large")
        }
        return result
    }

    static func patchActionScheme(
        profile: XcodeIntegration.Profile,
        targetID: String,
        applicationTarget: Hub.XcodeTarget,
        projectName: String,
        integrationRoot: String
    ) throws -> Data {
        guard let patch = profile.patch else {
            throw Hub.Error.invalidOnboarding("Hot Patch profile has no action settings")
        }
        let escapedTarget = xml(targetID)
        let escapedName = xml(patch.actionTargetName)
        let escapedProject = xml(projectName)
        let escapedConfiguration = xml(profile.configurationName)
        let escapedApplicationID = xml(applicationTarget.id)
        let escapedApplicationName = xml(applicationTarget.name)
        let escapedApplicationProduct = xml(
            applicationTarget.buildableName ?? applicationTarget.productName
        )
        let escapedScript = xml(ownedScript(
            "/bin/sh \"$SRCROOT/\(integrationRoot)/Profiles/\(profile.id)/patch.sh\""
        ))
        let source = """
        <?xml version="1.0" encoding="UTF-8"?>
        <Scheme version="1.7">
          <BuildAction parallelizeBuildables="NO" buildImplicitDependencies="NO">
            <PreActions>
              <ExecutionAction ActionType="Xcode.IDEStandardExecutionActionsCore.ExecutionActionType.ShellScriptAction">
                <ActionContent title="Helix Hub: Build \(xml(profile.id)) patch" scriptText="\(escapedScript)">
                  <EnvironmentBuildable>
                    <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="\(escapedApplicationID)" BuildableName="\(escapedApplicationProduct)" BlueprintName="\(escapedApplicationName)" ReferencedContainer="container:\(escapedProject).xcodeproj"/>
                  </EnvironmentBuildable>
                </ActionContent>
              </ExecutionAction>
            </PreActions>
            <BuildActionEntries>
              <BuildActionEntry buildForTesting="NO" buildForRunning="YES" buildForProfiling="NO" buildForArchiving="NO" buildForAnalyzing="NO">
                <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="\(escapedTarget)" BuildableName="\(escapedName)" BlueprintName="\(escapedName)" ReferencedContainer="container:\(escapedProject).xcodeproj"/>
              </BuildActionEntry>
            </BuildActionEntries>
          </BuildAction>
          <TestAction buildConfiguration="\(escapedConfiguration)" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES"/>
          <LaunchAction buildConfiguration="\(escapedConfiguration)" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES"/>
          <ProfileAction buildConfiguration="\(escapedConfiguration)" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES"/>
          <AnalyzeAction buildConfiguration="\(escapedConfiguration)"/>
          <ArchiveAction buildConfiguration="\(escapedConfiguration)" revealArchiveInOrganizer="NO"/>
        </Scheme>
        """
        return Data(source.utf8)
    }

    static func applicationScheme(
        applicationTarget: Hub.XcodeTarget,
        projectName: String,
        launchConfiguration: String,
        archiveConfiguration: String
    ) throws -> Data {
        guard applicationTarget.kind == .application else {
            throw Hub.Error.invalidOnboarding(
                "an application scheme requires an App target"
            )
        }
        let targetID = xml(applicationTarget.id)
        let targetName = xml(applicationTarget.name)
        let productName = xml(
            applicationTarget.buildableName ?? applicationTarget.productName
        )
        let project = xml(projectName)
        let launch = xml(launchConfiguration)
        let archive = xml(archiveConfiguration)
        let reference = """
        <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="\(targetID)" BuildableName="\(productName)" BlueprintName="\(targetName)" ReferencedContainer="container:\(project).xcodeproj"/>
        """
        let source = """
        <?xml version="1.0" encoding="UTF-8"?>
        <Scheme version="1.7">
          <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
            <BuildActionEntries>
              <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">
                \(reference)
              </BuildActionEntry>
            </BuildActionEntries>
          </BuildAction>
          <TestAction buildConfiguration="\(launch)" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES">
            <MacroExpansion>\(reference)</MacroExpansion>
          </TestAction>
          <LaunchAction buildConfiguration="\(launch)" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES">
            <BuildableProductRunnable runnableDebuggingMode="0">\(reference)</BuildableProductRunnable>
          </LaunchAction>
          <ProfileAction buildConfiguration="\(launch)" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES">
            <BuildableProductRunnable runnableDebuggingMode="0">\(reference)</BuildableProductRunnable>
          </ProfileAction>
          <AnalyzeAction buildConfiguration="\(launch)"/>
          <ArchiveAction buildConfiguration="\(archive)" revealArchiveInOrganizer="YES"/>
        </Scheme>
        """
        let data = Data(source.utf8)
        guard data.count <= 8 * 1_024 * 1_024 else {
            throw Hub.Error.invalidProject("generated Xcode scheme is unexpectedly large")
        }
        return data
    }

    private func requiredElement(_ name: String) throws -> XMLElement {
        guard let value = document.rootElement()?.elements(forName: name).first else {
            throw Hub.Error.invalidProject("shared scheme has no \(name)")
        }
        return value
    }

    private func appendAction(
        owner: XMLElement,
        containerName: String,
        title: String,
        script: String,
        target: Hub.XcodeTarget,
        projectName: String
    ) {
        let container: XMLElement
        if let existing = owner.elements(forName: containerName).first {
            container = existing
        } else {
            container = XMLElement(name: containerName)
            owner.insertChild(container, at: 0)
        }
        container.addChild(executionAction(
            title: title,
            script: script,
            target: target,
            projectName: projectName
        ))
    }

    private func removeOwnedAction(from owner: XMLElement, containerName: String) {
        guard let container = owner.elements(forName: containerName).first else { return }
        removeOwnedChildren(from: container)
        if container.children?.isEmpty != false {
            container.detach()
        }
    }

    private func removeOwnedChildren(from container: XMLElement) {
        for action in container.elements(forName: "ExecutionAction") {
            guard let content = action.elements(forName: "ActionContent").first else {
                continue
            }
            let title = content.attribute(forName: "title")?.stringValue ?? ""
            if title.hasPrefix("Helix Hub:"), isOwned(content) {
                action.detach()
            }
        }
    }

    private func executionAction(
        title: String,
        script: String,
        target: Hub.XcodeTarget,
        projectName: String
    ) -> XMLElement {
        let execution = XMLElement(name: "ExecutionAction")
        execution.addAttribute(Self.attribute(
            name: "ActionType",
            stringValue: "Xcode.IDEStandardExecutionActionsCore.ExecutionActionType.ShellScriptAction"
        ))
        let content = XMLElement(name: "ActionContent")
        content.addAttribute(Self.attribute(name: "title", stringValue: title))
        content.addAttribute(Self.attribute(name: "scriptText", stringValue: script))
        let environment = XMLElement(name: "EnvironmentBuildable")
        let reference = XMLElement(name: "BuildableReference")
        let attributes = [
            "BuildableIdentifier": "primary",
            "BlueprintIdentifier": target.id,
            "BuildableName": target.buildableName ?? target.productName,
            "BlueprintName": target.name,
            "ReferencedContainer": "container:\(projectName).xcodeproj",
        ]
        for key in attributes.keys.sorted() {
            reference.addAttribute(Self.attribute(
                name: key,
                stringValue: attributes[key] ?? ""
            ))
        }
        environment.addChild(reference)
        content.addChild(environment)
        execution.addChild(content)
        return execution
    }

    private func phaseScript(
        profile: XcodeIntegration.Profile,
        phase: String,
        integrationRoot: String
    ) -> String {
        Self.ownedScript(
            "/bin/sh \"$SRCROOT/\(integrationRoot)/Profiles/\(profile.id)/\(phase).sh\""
        )
    }

    private func isOwned(_ content: XMLElement) -> Bool {
        content.attribute(forName: "scriptText")?.stringValue?
            .hasPrefix(Self.ownedScriptMarker + " ") == true
    }

    private static func ownedScript(_ command: String) -> String {
        "\(ownedScriptMarker) \(command)"
    }

    private static func attribute(name: String, stringValue: String) -> XMLNode {
        XMLNode.attribute(withName: name, stringValue: stringValue) as! XMLNode
    }

    private static func xml(_ value: String) -> String {
        value.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }
}
}
#endif
