import Foundation
import HelixCompiler

extension FrontendReceipt {
/// Builds a source-local, uniquely named async thunk for OriginalCatalog.
/// Calling this thunk is statically resolved even when the decoded receiver is
/// a subclass, while copying the exact body retains private lookup and `super`.
enum AsyncOriginalThunk {
    typealias Object = FrontendReceipt.TypedAST.Object

    private struct Rewrite: Sendable {
        var utf8Offset: Int
        var token: String
        var replacement: String
    }

    private static let nestedFunctionContexts: Set<String> = [
        "accessor_decl", "class_decl", "constructor_decl", "destructor_decl",
        "enum_decl", "extension_decl", "func_decl", "macro_decl",
        "protocol_decl", "struct_decl", "subscript_decl",
    ]

    static func render(
        body: Object,
        bodyRange: (start: Int, end: Int),
        source: Data,
        locationMap: SourceTransform.LocationMap,
        logicalPath: String,
        originalFunctionName: String,
        thunkHeader: String,
        enclosingPrefix: String,
        enclosingSuffix: String
    ) throws -> String? {
        let lowerBound = bodyRange.start.addingReportingOverflow(1)
        guard !lowerBound.overflow,
              lowerBound.partialValue <= bodyRange.end,
              bodyRange.end < source.count,
              source[bodyRange.start] == UInt8(ascii: "{"),
              source[bodyRange.end] == UInt8(ascii: "}")
        else {
            throw FrontendReceipt.Error.malformedAST(
                "\(logicalPath): async original thunk has an invalid body range"
            )
        }

        guard let openingLocation = locationMap.location(
            atUTF8Offset: bodyRange.start
        ) else {
            throw FrontendReceipt.Error.malformedAST(
                "\(logicalPath): async original thunk has no source location"
            )
        }
        let rewrites = try magicLiteralRewrites(
            in: body,
            source: source,
            bodyRange: bodyRange,
            locationMap: locationMap,
            originalFunctionName: originalFunctionName,
            logicalPath: logicalPath
        )
        var copiedBody = source.subdata(
            in: lowerBound.partialValue..<bodyRange.end
        )
        for rewrite in rewrites.sorted(by: { $0.utf8Offset > $1.utf8Offset }) {
            let relativeOffset = rewrite.utf8Offset - lowerBound.partialValue
            copiedBody.replaceSubrange(
                relativeOffset..<(relativeOffset + rewrite.token.utf8.count),
                with: rewrite.replacement.utf8
            )
        }
        guard let copiedBodyText = String(data: copiedBody, encoding: .utf8) else {
            throw FrontendReceipt.Error.malformedAST(
                "\(logicalPath): async original body is not UTF-8"
            )
        }
        let locatedBody = BridgeGeneration.SourceBodyTransform.sourceLocatedBody(
            copiedBodyText,
            logicalPath: logicalPath,
            openingBraceLine: openingLocation.line,
            openingBraceColumn: openingLocation.column,
            closesSourceLocation: false
        )
        let comment = "// Generated by Helix: exact async original thunk."
        // The transformed file owns the matching closing directive. Reopen its
        // logical mapping after the copied body instead of closing it here.
        let restoredSourceLocation = "#sourceLocation(file: "
            + String(reflecting: logicalPath) + ", line: 1)"
        let rendered: String
        if enclosingPrefix.isEmpty {
            rendered = "\(comment)\n\(thunkHeader) {\n\(locatedBody)}\n"
                + restoredSourceLocation
        } else {
            rendered = """
            \(comment)
            \(enclosingPrefix)
                \(thunkHeader) {
            \(locatedBody)    }
            \(enclosingSuffix)
            \(restoredSourceLocation)
            """
        }
        return rendered.utf8.count <= 64 * 1_024
                && !rendered.unicodeScalars.contains(where: { $0.value == 0 })
            ? rendered : nil
    }

    private static func magicLiteralRewrites(
        in body: Object,
        source: Data,
        bodyRange: (start: Int, end: Int),
        locationMap: SourceTransform.LocationMap,
        originalFunctionName: String,
        logicalPath: String
    ) throws -> [Rewrite] {
        var rewritesByOffset: [Int: Rewrite] = [:]

        func record(
            _ object: Object,
            preservesOuterFunction: Bool
        ) throws {
            guard let kind = object["kind"] as? String else {
                throw FrontendReceipt.Error.malformedAST(
                    "\(logicalPath): magic literal has no kind"
                )
            }
            let replacement: String?
            switch kind {
            case "#function" where preservesOuterFunction:
                replacement = String(reflecting: originalFunctionName)
            case "#column":
                guard let range = sourceRange(in: object),
                      let location = locationMap.location(
                          atUTF8Offset: range.start
                      )
                else {
                    throw FrontendReceipt.Error.malformedAST(
                        "\(logicalPath): #column has no exact source location"
                    )
                }
                replacement = String(location.column)
            default:
                replacement = nil
            }
            guard let replacement else { return }
            guard let range = sourceRange(in: object) else {
                throw FrontendReceipt.Error.malformedAST(
                    "\(logicalPath): \(kind) has no exact source range"
                )
            }
            let tokenEnd = range.start.addingReportingOverflow(kind.utf8.count)
            guard !tokenEnd.overflow,
                  range.start > bodyRange.start,
                  range.start <= bodyRange.end,
                  tokenEnd.partialValue <= bodyRange.end,
                  source.subdata(
                      in: range.start..<tokenEnd.partialValue
                  ) == Data(kind.utf8)
            else {
                throw FrontendReceipt.Error.malformedAST(
                    "\(logicalPath): \(kind) is not bound to its source token"
                )
            }
            let rewrite = Rewrite(
                utf8Offset: range.start,
                token: kind,
                replacement: replacement
            )
            if let existing = rewritesByOffset[range.start],
               existing.token != rewrite.token
                    || existing.replacement != rewrite.replacement {
                throw FrontendReceipt.Error.malformedAST(
                    "\(logicalPath): overlapping magic-literal rewrites disagree"
                )
            }
            rewritesByOffset[range.start] = rewrite
        }

        func visit(_ value: Any, preservesOuterFunction: Bool) throws {
            if let object = value as? Object {
                let objectKind = object["_kind"] as? String
                if objectKind == "magic_identifier_literal_expr" {
                    try record(
                        object,
                        preservesOuterFunction: preservesOuterFunction
                    )
                    return
                }
                let nestedContext = objectKind.map { kind in
                    guard nestedFunctionContexts.contains(kind) else {
                        return false
                    }
                    // The typed AST represents `defer` as an implicit helper,
                    // but Swift magic literals inside it retain the enclosing
                    // source function's identity. Explicit local functions do
                    // establish a new `#function` context.
                    return kind != "func_decl"
                        || object["implicit"] as? Bool != true
                } == true
                for child in object.values {
                    try visit(
                        child,
                        preservesOuterFunction:
                            preservesOuterFunction && !nestedContext
                    )
                }
            } else if let values = value as? [Any] {
                for child in values {
                    try visit(
                        child,
                        preservesOuterFunction: preservesOuterFunction
                    )
                }
            }
        }

        try visit(body, preservesOuterFunction: true)
        return Array(rewritesByOffset.values)
    }

    private static func sourceRange(in object: Object) -> (start: Int, end: Int)? {
        guard let range = object["range"] as? Object,
              let start = (range["start"] as? NSNumber)?.intValue,
              let end = (range["end"] as? NSNumber)?.intValue
        else { return nil }
        return (start, end)
    }
}
}
