import Foundation
import HelixCore
import HelixInterface

extension ShellBuild {
public struct BridgeProviderSource: Hashable, Sendable {
    public var path: String
    public var contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

/// Emits the stable process-level provider used by Runtime products. This file
/// is compiled into HelixBridge.o inside DerivedData and is never added to an
/// Xcode project or imported by application source.
public struct BridgeProviderGenerator: Sendable {
    public init() {}

    public static func sourcePath(moduleName: String) -> String {
        "Generated/\(moduleName)Bridge.Provider.swift"
    }

    public func generate(
        archive: InterfaceArchive.Archive,
        reloadIndexHash: Core.Digest
    ) throws -> ShellBuild.BridgeProviderSource {
        try archive.validate()
        let moduleName = archive.metadata.frontendInvocation.moduleName
        let bridgeType = "\(moduleName)Bridge"
        let target = try parseTarget(archive.metadata.targetTriple)
        let imports = archive.nativeImports.compactMap { record -> String? in
            guard record.isEmittedToDevice, let id = record.id else { return nil }
            return "Core.NativeImportID(rawValue: \(id.rawValue))"
        }.sorted()
        let capabilities = archive.capabilities.sorted().map {
            "Core.Capability(rawValue: \(String(reflecting: $0.rawValue)))"
        }
        let contents = """
        // Generated by Helix Shell Build. Do not edit.
        import HelixCore
        import HelixRuntime

        private enum HelixBridgeProviderStorage {
            static let provider: Runtime.BridgeProvider? = {
                do {
                    let descriptor = Runtime.BridgeDescriptor(
                        bundleID: \(String(reflecting: archive.metadata.bundleID)),
                        buildNumber: \(String(reflecting: archive.metadata.buildNumber)),
                        shellNamespaceID: Core.ShellNamespaceID(
                            rawValue: try Core.Digest(
                                hex: \(String(reflecting: archive.metadata.shellNamespaceID.rawValue.hex))
                            )
                        ),
                        shellInterfaceHash: \(bridgeType).interfaceHash,
                        minimumOSVersion: \(render(archive.metadata.minimumOS)),
                        compatibility: \(render(archive.compatibility)),
                        capabilities: Set(\(renderArray(capabilities))),
                        nativeImportIDs: Set(\(renderArray(imports))),
                        platform: .\(target.platformCase),
                        architecture: \(String(reflecting: target.architecture)),
                        xcodeBuild: \(String(reflecting: archive.metadata.xcodeBuild)),
                        liveReloadIndexHash: try Core.Digest(
                            hex: \(String(reflecting: reloadIndexHash.hex))
                        ),
                        runtimeImageIdentity: .current
                    )
                    try descriptor.validate()
                    return Runtime.BridgeProvider(
                        descriptor: descriptor,
                        makeRuntime: { registry, observer in
                            try \(bridgeType).makeRuntime(
                                registry: registry,
                                observer: observer
                            )
                        },
                        makeShellInterface: {
                            try \(bridgeType).makeShellInterface()
                        },
                        install: { runtime in
                            try \(bridgeType).bootstrap(using: runtime)
                        }
                    )
                } catch {
                    return nil
                }
            }()
        }

        @_cdecl("hlx_bridge_provider_v1")
        public func helixBridgeProviderV1() -> UnsafeMutableRawPointer? {
            guard let provider = HelixBridgeProviderStorage.provider else { return nil }
            return Unmanaged.passUnretained(provider).toOpaque()
        }

        """
        return .init(
            path: Self.sourcePath(moduleName: moduleName),
            contents: contents
        )
    }

    private func parseTarget(
        _ triple: String
    ) throws -> (architecture: String, platformCase: String) {
        guard let architecture = triple.split(separator: "-").first.map(String.init),
              ["arm64", "x86_64"].contains(architecture)
        else {
            throw ShellBuild.Error.invalidInput(
                "Bridge provider target architecture is unsupported"
            )
        }
        let lowercased = triple.lowercased()
        if lowercased.contains("-apple-ios") {
            return (
                architecture,
                lowercased.contains("-simulator") ? "iOSSimulator" : "iOS"
            )
        }
        if lowercased.contains("-apple-macos") {
            return (architecture, "macOS")
        }
        throw ShellBuild.Error.invalidInput(
            "Bridge provider target platform is unsupported"
        )
    }

    private func render(_ version: Core.SemanticVersion) -> String {
        "Core.SemanticVersion(\(version.major), \(version.minor), \(version.patch))"
    }

    private func render(_ compatibility: Core.Compatibility) -> String {
        """
        Core.Compatibility(
            runtime: \(render(compatibility.runtime)),
            bytecode: \(render(compatibility.bytecode)),
            interfaceArchive: \(render(compatibility.interfaceArchive)),
            compilerFingerprint: \(String(reflecting: compatibility.compilerFingerprint))
        )
        """
    }

    private func renderArray(_ values: [String]) -> String {
        guard !values.isEmpty else { return "[]" }
        return "[\n" + values.map { "                            \($0)" }
            .joined(separator: ",\n") + "\n                        ]"
    }
}
}
