import Foundation
import HelixCompiler
import HelixCore
import HelixDevProtocol
import HelixInterface

extension ShellBuild {
/// Non-secret service trust and one-time invitation compiled into a Dev Shell.
public struct HubBinding: Hashable, Sendable {
    public var reservation: Pairing.Reservation
    public var spkiSHA256: Core.Digest

    public init(
        reservation: Pairing.Reservation,
        spkiSHA256: Core.Digest
    ) throws {
        try reservation.validate()
        guard reservation.kind == .automaticXcode else {
            throw ShellBuild.Error.invalidInput(
                "a Dev Shell requires an automatic Xcode reservation"
            )
        }
        self.reservation = reservation
        self.spkiSHA256 = spkiSHA256
    }
}

public struct DevContractSource: Hashable, Sendable {
    public var path: String
    public var contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

/// Emits a Debug-only typed factory beside the permanent Bridge. The values
/// originate from the same HLXI and Reload Index that the Helix service accepts.
public struct DevContractGenerator: Sendable {
    public init() {}

    public static func sourcePath(moduleName: String) -> String {
        "Generated/\(moduleName)Bridge.DevBuildContract.swift"
    }

    public func generate(
        archive: InterfaceArchive.Archive,
        reloadIndexHash: Core.Digest,
        hubBinding: ShellBuild.HubBinding? = nil
    ) throws -> ShellBuild.DevContractSource {
        try archive.validate()
        let moduleName = archive.metadata.frontendInvocation.moduleName
        let target = try parseTarget(archive.metadata.targetTriple)
        let bridgeType = "\(moduleName)Bridge"
        let path = Self.sourcePath(moduleName: moduleName)
        let hubContract: String
        if let hubBinding {
            hubContract = """

            private enum \(bridgeType)HubContractStorage {
                static let value: DevRuntime.HubContract = {
                    try! DevRuntime.HubContract(
                        expectedSPKIHash: try! Core.Digest(
                            hex: \(String(reflecting: hubBinding.spkiSHA256.hex))
                        ),
                        automaticPairingCode: try! Pairing.Code(
                            \(String(reflecting: hubBinding.reservation.code.rawValue))
                        )
                    )
                }()
            }

            @_cdecl("hlx_dev_hub_contract_v1")
            public func hlx_dev_hub_contract_v1() -> UnsafeMutableRawPointer? {
                Unmanaged.passUnretained(
                    \(bridgeType)HubContractStorage.value
                ).toOpaque()
            }
            """
        } else {
            hubContract = ""
        }
        let contents = """
        // Generated by Helix Shell Build. Do not edit.
        #if DEBUG
        \(BridgeGeneration.RuntimeImports.development)

        extension \(bridgeType) {
            public static func makeDevBuildContract() throws -> DevRuntime.BuildContract {
                try DevRuntime.BuildContract(
                    bundleID: \(String(reflecting: archive.metadata.bundleID)),
                    platform: .\(target.platformCase),
                    architecture: \(String(reflecting: target.architecture)),
                    xcodeBuild: \(String(reflecting: archive.metadata.xcodeBuild)),
                    swiftCompilerFingerprint: \(String(reflecting: archive.compatibility.compilerFingerprint)),
                    liveReloadIndexHash: try Core.Digest(
                        hex: \(String(reflecting: reloadIndexHash.hex))
                    ),
                    runtimeImageIdentity: .current
                )
            }
        }
        \(hubContract)
        #endif

        """
        return .init(path: path, contents: contents)
    }

    private func parseTarget(
        _ triple: String
    ) throws -> (architecture: String, platformCase: String) {
        guard let architecture = triple.split(separator: "-").first.map(String.init),
              ["arm64", "x86_64"].contains(architecture)
        else {
            throw ShellBuild.Error.invalidInput(
                "Dev BuildContract target architecture is unsupported"
            )
        }
        let lowercased = triple.lowercased()
        let platformCase: String
        if lowercased.contains("-apple-ios") {
            platformCase = lowercased.contains("-simulator") ? "iOSSimulator" : "iOS"
        } else if lowercased.contains("-apple-macos") {
            platformCase = "macOS"
        } else {
            throw ShellBuild.Error.invalidInput(
                "Dev BuildContract target platform is unsupported"
            )
        }
        return (architecture, platformCase)
    }
}
}
