import Foundation
import HelixCompiler
import HelixCore
import HelixDevProtocol
import HelixInterface

extension ShellBuild {
/// Temporary service trust and one-time invitation compiled into a Dev Shell.
public struct HubBinding: Hashable, Sendable {
    public var reservation: Pairing.Reservation
    public var spkiSHA256: Core.Digest

    public init(
        reservation: Pairing.Reservation,
        spkiSHA256: Core.Digest
    ) throws {
        try reservation.validate()
        guard reservation.kind == .automaticXcode else {
            throw ShellBuild.Error.invalidInput(
                "a Dev Shell requires an automatic Xcode reservation"
            )
        }
        self.reservation = reservation
        self.spkiSHA256 = spkiSHA256
    }
}

public struct HubContractSource: Hashable, Sendable {
    public var path: String
    public var contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

/// Emits the small, invitation-specific source separately from the stable
/// application Bridge so a new automatic pairing reservation cannot invalidate
/// the expensive Bridge object cache.
public struct HubContractGenerator: Sendable {
    public init() {}

    public static func sourcePath(moduleName: String) -> String {
        "Generated/\(moduleName)Bridge.HubContract.swift"
    }

    public func generate(
        archive: InterfaceArchive.Archive,
        binding: ShellBuild.HubBinding
    ) throws -> ShellBuild.HubContractSource {
        try archive.validate()
        let moduleName = archive.metadata.frontendInvocation.moduleName
        let storageType = "\(moduleName)BridgeHubContractStorage"
        let path = Self.sourcePath(moduleName: moduleName)
        let contents = """
        // Generated by Helix Shell Build. Do not edit.
        #if DEBUG
        \(BridgeGeneration.RuntimeImports.development)

        private enum \(storageType) {
            static let value: DevRuntime.HubContract = {
                try! DevRuntime.HubContract(
                    expectedSPKIHash: try! Core.Digest(
                        hex: \(String(reflecting: binding.spkiSHA256.hex))
                    ),
                    automaticPairingCode: try! Pairing.Code(
                        \(String(reflecting: binding.reservation.code.rawValue))
                    )
                )
            }()
        }

        @_cdecl("hlx_dev_hub_contract_v1")
        public func hlx_dev_hub_contract_v1() -> UnsafeMutableRawPointer? {
            Unmanaged.passUnretained(\(storageType).value).toOpaque()
        }
        #endif

        """
        return .init(path: path, contents: contents)
    }
}
}
