import Foundation
import HelixCore
import HelixInterface

extension ShellBuild {
public struct DevContractSource: Hashable, Sendable {
    public var path: String
    public var contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

/// Emits a Debug-only typed factory beside the permanent Bridge. The values
/// originate from the same HLXI and Reload Index that the Mac daemon accepts.
public struct DevContractGenerator: Sendable {
    public init() {}

    public static func sourcePath(moduleName: String) -> String {
        "Generated/\(moduleName)Bridge.DevBuildContract.swift"
    }

    public func generate(
        archive: InterfaceArchive.Archive,
        reloadIndexHash: Core.Digest
    ) throws -> ShellBuild.DevContractSource {
        try archive.validate()
        let moduleName = archive.metadata.frontendInvocation.moduleName
        let target = try parseTarget(archive.metadata.targetTriple)
        let bridgeType = "\(moduleName)Bridge"
        let path = Self.sourcePath(moduleName: moduleName)
        let contents = """
        // Generated by Helix Shell Build. Do not edit.
        #if DEBUG
        import HelixCore
        import HelixDevProtocol
        import HelixDevRuntime

        extension \(bridgeType) {
            public static func makeDevBuildContract() throws -> DevRuntime.BuildContract {
                try DevRuntime.BuildContract(
                    bundleID: \(String(reflecting: archive.metadata.bundleID)),
                    platform: .\(target.platformCase),
                    architecture: \(String(reflecting: target.architecture)),
                    xcodeBuild: \(String(reflecting: archive.metadata.xcodeBuild)),
                    swiftCompilerFingerprint: \(String(reflecting: archive.compatibility.compilerFingerprint)),
                    liveReloadIndexHash: try Core.Digest(
                        hex: \(String(reflecting: reloadIndexHash.hex))
                    ),
                    runtimeImageIdentity: .current
                )
            }
        }
        #endif

        """
        return .init(path: path, contents: contents)
    }

    private func parseTarget(
        _ triple: String
    ) throws -> (architecture: String, platformCase: String) {
        guard let architecture = triple.split(separator: "-").first.map(String.init),
              ["arm64", "x86_64"].contains(architecture)
        else {
            throw ShellBuild.Error.invalidInput(
                "Dev BuildContract target architecture is unsupported"
            )
        }
        let lowercased = triple.lowercased()
        let platformCase: String
        if lowercased.contains("-apple-ios") {
            platformCase = lowercased.contains("-simulator") ? "iOSSimulator" : "iOS"
        } else if lowercased.contains("-apple-macos") {
            platformCase = "macOS"
        } else {
            throw ShellBuild.Error.invalidInput(
                "Dev BuildContract target platform is unsupported"
            )
        }
        return (architecture, platformCase)
    }
}
}
