import Foundation
import HelixCore

extension XcodeIntegration {
public struct ProfileContract: Codable, Hashable, Sendable {
    public static let currentSchemaVersion: UInt16 = 1

    public var schemaVersion: UInt16
    public var profileID: String
    public var workflow: XcodeIntegration.Workflow
    public var runtimePackageProduct: String
    public var featureModuleName: String
    public var commonConfiguration: String
    public var featureConfiguration: String
    public var applicationConfiguration: String
    public var bridgePhaseScript: String

    public init(
        profile: XcodeIntegration.Profile,
        feature: XcodeIntegration.Feature
    ) {
        schemaVersion = Self.currentSchemaVersion
        profileID = profile.id
        workflow = profile.workflow
        runtimePackageProduct = profile.runtimePackageProduct
        featureModuleName = feature.moduleName
        let root = "Profiles/\(profile.id)"
        commonConfiguration = "\(root)/Profile.xcconfig"
        featureConfiguration = "\(root)/Feature.xcconfig"
        applicationConfiguration = "\(root)/Application.xcconfig"
        bridgePhaseScript = "\(root)/bridge.sh"
    }
}

public struct KitArtifact: Codable, Hashable, Sendable {
    public var path: String
    public var byteCount: UInt64
    public var sha256: Core.Digest
    public var permissions: UInt16

    public init(path: String, data: Data, permissions: UInt16 = 0o644) {
        self.path = path
        byteCount = UInt64(data.count)
        sha256 = .sha256(data)
        self.permissions = permissions
    }
}

public struct KitManifest: Codable, Hashable, Sendable {
    public static let currentSchemaVersion: UInt16 = 1

    public var schemaVersion: UInt16
    public var hostPlanSHA256: Core.Digest
    public var profiles: [XcodeIntegration.ProfileContract]
    public var artifacts: [XcodeIntegration.KitArtifact]
}

public struct KitOutput: Sendable {
    public var manifest: XcodeIntegration.KitManifest
    public var artifacts: [String: Data]
    public var executablePaths: Set<String>
}

/// Produces deterministic files that are checked by Xcode build phases. The
/// generated scripts contain no build logic; they dispatch to the versioned
/// `helix xcode phase` API so projects do not accumulate private shell code.
public struct KitGenerator: Sendable {
    public init() {}

    public func generate(
        plan: XcodeIntegration.HostPlan
    ) throws -> XcodeIntegration.KitOutput {
        try plan.validate()
        let planBytes = try XcodeIntegration.HostPlanCodec.encode(plan)
        var artifacts: [String: Data] = [:]
        try insert(planBytes, at: "HostPlan.json", into: &artifacts)
        try insert(
            Data(renderSharedConfiguration(plan: plan).utf8),
            at: "Shared/Helix.xcconfig",
            into: &artifacts
        )
        try insert(
            Data(renderPhaseDispatcher().utf8),
            at: "Scripts/helix-phase.sh",
            into: &artifacts
        )
        try insert(
            XcodeIntegration.CompilerCapture.proxyScript(),
            at: XcodeIntegration.CompilerCapture.integrationProxyPath,
            into: &artifacts
        )

        var contracts: [XcodeIntegration.ProfileContract] = []
        for profile in plan.profiles {
            let feature = try plan.feature(id: profile.featureID)
            let contract = XcodeIntegration.ProfileContract(
                profile: profile,
                feature: feature
            )
            contracts.append(contract)
            try generate(
                profile: profile,
                feature: feature,
                plan: plan,
                contract: contract,
                into: &artifacts
            )
        }
        let sameTargetNames = Set(try plan.profiles.compactMap { profile in
            let feature = try plan.feature(id: profile.featureID)
            return feature.targetName == profile.applicationTargetName
                ? feature.targetName : nil
        })
        for targetName in sameTargetNames.sorted() {
            try insert(
                Data("// Generated by Helix. Do not edit.\n".utf8),
                at: XcodeIntegration.CompilerCapture.targetTriggerPath(
                    targetName: targetName
                ),
                into: &artifacts
            )
        }
        let guide = renderGuide(plan: plan, contracts: contracts)
        try insert(Data(guide.utf8), at: "Integration.md", into: &artifacts)

        let executablePaths = Set(
            artifacts.keys.filter {
                $0.hasSuffix(".sh") || $0.hasSuffix("/Compiler/swiftc")
            }
        )
        let records = artifacts.map {
            XcodeIntegration.KitArtifact(
                path: $0.key,
                data: $0.value,
                permissions: executablePaths.contains($0.key) ? 0o755 : 0o644
            )
        }.sorted { $0.path < $1.path }
        let manifest = XcodeIntegration.KitManifest(
            schemaVersion: XcodeIntegration.KitManifest.currentSchemaVersion,
            hostPlanSHA256: .sha256(planBytes),
            profiles: contracts.sorted { $0.profileID < $1.profileID },
            artifacts: records
        )
        try insert(
            try Core.CanonicalJSON.encode(manifest),
            at: "IntegrationManifest.json",
            into: &artifacts
        )
        return .init(
            manifest: manifest,
            artifacts: artifacts,
            executablePaths: executablePaths
        )
    }

    private func generate(
        profile: XcodeIntegration.Profile,
        feature: XcodeIntegration.Feature,
        plan: XcodeIntegration.HostPlan,
        contract: XcodeIntegration.ProfileContract,
        into artifacts: inout [String: Data]
    ) throws {
        let root = "Profiles/\(profile.id)"
        try insert(
            try Core.CanonicalJSON.encode(contract),
            at: "\(root)/ProfileContract.json",
            into: &artifacts
        )
        try insert(
            Data(renderProfileConfiguration(profile: profile, plan: plan).utf8),
            at: contract.commonConfiguration,
            into: &artifacts
        )
        try insert(
            Data(renderFeatureConfiguration(feature: feature).utf8),
            at: contract.featureConfiguration,
            into: &artifacts
        )
        try insert(
            Data(renderApplicationConfiguration(workflow: profile.workflow).utf8),
            at: contract.applicationConfiguration,
            into: &artifacts
        )
        try insert(
            XcodeIntegration.CompilerCapture.proxyScript(
                postCompileScriptName: "post-compile.sh"
            ),
            at: XcodeIntegration.CompilerCapture.profileProxyPath(
                profileID: profile.id
            ),
            into: &artifacts
        )
        try insert(
            Data(renderPostCompileWrapper(profileID: profile.id).utf8),
            at: XcodeIntegration.CompilerCapture.profilePostCompilePath(
                profileID: profile.id
            ),
            into: &artifacts
        )
        for phase in phaseNames(for: profile) {
            try insert(
                Data(renderPhaseWrapper(
                    profileID: profile.id,
                    configurationName: profile.configurationName,
                    phase: phase
                ).utf8),
                at: "\(root)/\(phase).sh",
                into: &artifacts
            )
        }
    }

    private func renderSharedConfiguration(plan: XcodeIntegration.HostPlan) -> String {
        """
        // Generated by Helix. Do not edit.
        HELIX_INTEGRATION_ROOT = $(SRCROOT)/\(plan.integrationRoot)
        HELIX_HOST_PLAN = $(HELIX_INTEGRATION_ROOT)/HostPlan.json
        HELIX_BUILD_ROOT = $(BUILT_PRODUCTS_DIR)/HelixGenerated
        // Helix phases consume compiler outputs discovered at build time and
        // cannot be represented by Xcode's static user-script file sandbox.
        ENABLE_USER_SCRIPT_SANDBOXING = NO

        """
    }

    private func renderProfileConfiguration(
        profile: XcodeIntegration.Profile,
        plan: XcodeIntegration.HostPlan
    ) -> String {
        let patchSettings: String
        if let patch = profile.patch {
            patchSettings = """
            HELIX_PATCH_RECIPE = $(SRCROOT)/\(patch.recipePath)
            HELIX_PATCH_CERTIFICATE = $(SRCROOT)/\(patch.signingCertificatePath)
            HELIX_PATCH_TRUSTED_ROOT = $(SRCROOT)/\(patch.trustedRootPath)
            HELIX_PATCH_PRIVATE_KEY = $(SRCROOT)/\(patch.privateKeyPath)
            HELIX_PATCH_OUTPUT_ROOT = $(SRCROOT)/\(patch.outputRoot)
            \(patch.simulatorInboxPath.map {
                "HELIX_PATCH_SIMULATOR_INBOX = \($0)"
            } ?? "")

            """
        } else {
            patchSettings = ""
        }
        return """
        // Generated by Helix. Do not edit.
        #include "../../Shared/Helix.xcconfig"
        HELIX_PROFILE_ID = \(profile.id)
        HELIX_WORKFLOW = \(profile.workflow.rawValue)
        HELIX_RUNTIME_PRODUCT = \(profile.runtimePackageProduct)
        HELIX_PROFILE_OUTPUT_DIR = $(HELIX_BUILD_ROOT)/\(profile.id)
        HELIX_SHELL_OUTPUT_DIR = $(HELIX_PROFILE_OUTPUT_DIR)/Shell
        HELIX_FINAL_ARCHIVE = $(HELIX_PROFILE_OUTPUT_DIR)/Shell.final.hlxi
        HELIX_BRIDGE_OBJECT = $(HELIX_PROFILE_OUTPUT_DIR)/Bridge/HelixBridge.o
        HELIX_BOOTSTRAP_OBJECT = $(HELIX_PROFILE_OUTPUT_DIR)/Bridge/HelixBootstrap.o
        HELIX_DEV_CONFIGURATION = $(HELIX_PROFILE_OUTPUT_DIR)/HelixDev.json
        \(patchSettings)
        """.trimmingCharacters(in: .newlines) + "\n"
    }

    private func renderFeatureConfiguration(
        feature: XcodeIntegration.Feature
    ) -> String {
        return """
        // Generated by Helix. Do not edit.
        #include "Profile.xcconfig"
        PRODUCT_MODULE_NAME = \(feature.moduleName)
        LD_DYLIB_INSTALL_NAME = @rpath/$(EXECUTABLE_PATH)
        OTHER_SWIFT_FLAGS = $(inherited) -Xfrontend -enable-private-imports -Xfrontend -enable-implicit-dynamic -Xfrontend -enable-dynamic-replacement-chaining -user-module-version "$(CURRENT_PROJECT_VERSION)"
        HELIX_REAL_SWIFT_EXEC = $(TOOLCHAIN_DIR)/usr/bin/swiftc
        SWIFT_EXEC = $(HELIX_INTEGRATION_ROOT)/\(XcodeIntegration.CompilerCapture.integrationProxyPath)
        SWIFT_USE_INTEGRATED_DRIVER = NO
        // XCBuild's supplemental linker response is emitted by its integrated driver.
        // Swift object autolinking remains responsible for framework/library imports.
        SWIFT_GENERATE_ADDITIONAL_LINKER_ARGS = NO

        """.trimmingCharacters(in: .newlines) + "\n"
    }

    private func renderApplicationConfiguration(
        workflow: XcodeIntegration.Workflow
    ) -> String {
        let hubProvider = workflow == .liveReload
            ? " -Xlinker -u -Xlinker _hlx_dev_hub_contract_v1"
            : ""
        let developmentSupport = workflow == .liveReload
            ? " -framework HelixDevSupport" : ""
        let frameworkSearch = workflow == .liveReload
            ? "FRAMEWORK_SEARCH_PATHS = $(inherited) \"$(BUILT_PRODUCTS_DIR)/PackageFrameworks\"\n"
            : ""
        return """
        // Generated by Helix. Do not edit.
        #include "Profile.xcconfig"
        \(frameworkSearch)OTHER_LDFLAGS = $(inherited) "$(HELIX_BRIDGE_OBJECT)" "$(HELIX_BOOTSTRAP_OBJECT)" -Xlinker -u -Xlinker _hlx_bridge_provider_v1\(hubProvider)\(developmentSupport)

        """
    }

    private func renderPhaseDispatcher() -> String {
        """
        #!/bin/sh
        set -eu

        phase="${1:?missing Helix Xcode phase}"
        : "${HELIX_HOST_PLAN:?HELIX_HOST_PLAN is not configured}"
        : "${HELIX_PROFILE_ID:?HELIX_PROFILE_ID is not configured}"

        # Xcode can invoke target phases and Scheme post-actions for non-product
        # actions. They have no linked App to finalize or audit and must not
        # materialize a new Shell baseline.
        case "${ACTION:-}" in
            clean|analyze|installhdrs|installsrc)
                exit 0
                ;;
        esac

        if [ "${ENABLE_PREVIEWS:-NO}" = "YES" ]; then
            exit 0
        fi

        # Xcode exports these build-setting names, while Swift Driver reserves
        # the SWIFT_DEBUG_* environment namespace for its own diagnostics.
        unset SWIFT_DEBUG_INFORMATION_FORMAT SWIFT_DEBUG_INFORMATION_VERSION

        helix_executable="${HELIX_EXECUTABLE:-}"
        service_record="${HOME:?}/Library/Application Support/Helix/Service.json"
        if [ -z "$helix_executable" ] && [ -f "$service_record" ] && [ ! -L "$service_record" ]; then
            record_owner=$(/usr/bin/stat -f "%u" "$service_record" 2>/dev/null || true)
            record_mode=$(/usr/bin/stat -f "%Lp" "$service_record" 2>/dev/null || true)
            if [ "$record_owner" = "$(/usr/bin/id -u)" ] && [ "$record_mode" = "600" ]; then
                record_schema=$(
                    /usr/bin/plutil -extract schemaVersion raw -o - "$service_record" 2>/dev/null || true
                )
                record_pid=$(
                    /usr/bin/plutil -extract processIdentifier raw -o - "$service_record" 2>/dev/null || true
                )
                case "$record_pid" in
                    ''|*[!0-9]*) record_pid=0 ;;
                esac
                if [ "$record_schema" = "1" ] && [ "$record_pid" -gt 1 ] \
                    && /bin/kill -0 "$record_pid" 2>/dev/null; then
                    helix_executable=$(
                        /usr/bin/plutil -extract toolExecutablePath raw -o - "$service_record" 2>/dev/null || true
                    )
                fi
            fi
        fi
        if [ -z "$helix_executable" ]; then
            helix_executable=$(command -v helix 2>/dev/null || true)
        fi
        if [ -z "$helix_executable" ] || ! command -v "$helix_executable" >/dev/null 2>&1; then
            echo "error: no Helix build tool is available; open Helix and try again" >&2
            echo "error: headless workflows may install helix on PATH or set HELIX_EXECUTABLE" >&2
            exit 1
        fi

        if [ "$phase" = post-compile ]; then
            capture="${2:?missing Swift compiler capture}"
            exec "$helix_executable" xcode post-compile \
                --plan "$HELIX_HOST_PLAN" \
                --profile "$HELIX_PROFILE_ID" \
                --capture "$capture"
        fi

        exec "$helix_executable" xcode phase \
            --plan "$HELIX_HOST_PLAN" \
            --profile "$HELIX_PROFILE_ID" \
            --phase "$phase"

        """
    }

    private func renderPostCompileWrapper(profileID: String) -> String {
        return """
        #!/bin/sh
        set -eu

        capture="${1:?missing Swift compiler capture}"
        script_directory=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
        integration_root=$(CDPATH= cd -- "$script_directory/../../.." && pwd -P)
        export HELIX_INTEGRATION_ROOT="$integration_root"
        export HELIX_HOST_PLAN="$integration_root/HostPlan.json"
        export HELIX_PROFILE_ID="\(profileID)"

        exec /bin/sh "$integration_root/Scripts/helix-phase.sh" post-compile "$capture"

        """
    }

    private func renderPhaseWrapper(
        profileID: String,
        configurationName: String,
        phase: String
    ) -> String {
        let expectedConfiguration = shellLiteral(configurationName)
        return """
        #!/bin/sh
        set -eu

        # Target phases exist at the target level, while one Helix profile owns
        # only one build configuration. Unconfigured configurations are normal.
        if [ "${CONFIGURATION:-}" != \(expectedConfiguration) ]; then
            exit 0
        fi
        script_directory=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
        integration_root=$(CDPATH= cd -- "$script_directory/../.." && pwd -P)

        # Keep wrappers usable from both target phases and Scheme actions.
        export HELIX_INTEGRATION_ROOT="$integration_root"
        export HELIX_HOST_PLAN="$integration_root/HostPlan.json"
        export HELIX_PROFILE_ID="\(profileID)"

        exec /bin/sh "${HELIX_INTEGRATION_ROOT:?}/Scripts/helix-phase.sh" \(phase)

        """
    }

    private func shellLiteral(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\"'\"'") + "'"
    }

    private func phaseNames(for profile: XcodeIntegration.Profile) -> [String] {
        switch profile.workflow {
        case .hotPatch:
            profile.patch == nil
                ? ["prepare", "bridge", "finalize", "audit"]
                : ["prepare", "bridge", "finalize", "audit", "patch"]
        case .liveReload:
            ["prepare", "bridge", "finalize", "live-register"]
        }
    }

    private func renderGuide(
        plan: XcodeIntegration.HostPlan,
        contracts: [XcodeIntegration.ProfileContract]
    ) -> String {
        let orderedContracts = contracts.sorted { $0.profileID < $1.profileID }
        let profiles = zip(orderedContracts, plan.profiles).map { contract, profile in
            let common = """
            ## `\(contract.profileID)` (`\(profile.workflow.rawValue)`)

            - App target: `\(profile.applicationTargetName)`
            - Source target: `\((try? plan.feature(id: profile.featureID).targetName) ?? profile.featureID)`
            - Scheme and configuration: `\(profile.schemeName)` / `\(profile.configurationName)`
            - App product: `\(contract.runtimePackageProduct)` (linked automatically)

            Hub owns the target wrapper, compiler capture, generated trigger, runtime
            bootstrap, and Scheme action. Swift source membership is read from the successful
            Xcode compile, so adding, moving, deleting, or generating a source needs no Helix
            file list or policy update. Generated Bridge code remains in DerivedData.
            """
            switch profile.workflow {
            case .hotPatch:
                let actionScheme = profile.patch?.actionSchemeName ?? "Helix Build Patch"
                return common + """

                Build or archive the selected App configuration once. The installed Scheme
                action records the compiler, SDK, App identity, and generated interface for
                that build automatically. Build Scheme `\(actionScheme)` when creating a
                signed patch for it; no second App target or copied build settings are needed.
                """
            case .liveReload:
                return common + """

                Keep Helix open and use Xcode Run. The installed Scheme action registers the
                finished App, while the automatic runtime discovers and authenticates the local
                Hub. No LLDB file, launch variable, host address, pairing secret, runtime import,
                or initialization call is required.
                """
            }
        }.joined(separator: "\n\n")
        return """
        # Helix Xcode integration

        This directory is owned by Helix Hub and generated automatically. It is
        an implementation record, not a setup checklist. Reapply integration
        from Helix instead of editing these files.

        \(profiles)

        Project: `\(plan.projectPath)`
        """ + "\n"
    }

    private func insert(
        _ data: Data,
        at path: String,
        into artifacts: inout [String: Data]
    ) throws {
        guard artifacts.updateValue(data, forKey: path) == nil else {
            throw XcodeIntegration.Error.outputCollision(path)
        }
    }
}
}
